<?php
require_once '/usr/share/php/PHPUnit/Framework/TestCase.php';

require_once '/var/www/local_security/mportal/attendance/SystemParameters.php';
require_once '/var/www/mportal/FwCommon/FwBaseClass.php';

/**
 * Test class for FwBaseClass.
 * Generated by PHPUnit on 2010-03-29 at 03:14:15.
 */
class FwBaseClassTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var FwBaseClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FwBaseClass();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testChangeMinuteFromTime().
     */
    public function testChangeMinuteFromTime()
    {
        $this->assertEquals("60", $this->object->changeMinuteFromTime("01:00"));
    }
}
?>

